---
- name: Set hostname
  become: true
  hostname:
    name: backuppi.pagdot.at

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - sudo
    - nano
    - git
    - fuse
    - openssh-client
  become: true

- name: Setup system time
  import_role:
    name: geerlingguy.ntp
  vars:
    ntp_timezone: Europe/Vienna
  become: true
