---
- name: Check if resticprofile is installed
  shell: which resticprofile
  register: resticprofile_installed
  ignore_errors: true
  changed_when: false

- name: Check resticprofile version
  shell: resticprofile version
  register: resticprofile_installed_version
  when: resticprofile_installed.rc == 0
  changed_when: false

- name: Download resticprofile archive
  get_url: 
    url: "https://github.com/creativeprojects/resticprofile/releases/download/v{{ resticprofile_version }}/resticprofile_{{ resticprofile_version }}_linux_armv7.tar.gz"
    dest: /tmp/
  when: (resticprofile_installed.rc != 0) or not (("resticprofile version " + resticprofile_version) in resticprofile_installed_version.stdout)

- name: Unpack resticprofile binary from archive
  unarchive:
    src: "/tmp/resticprofile_{{ resticprofile_version }}_linux_armv7.tar.gz"
    dest: /tmp/
    remote_src: true
  when: (resticprofile_installed.rc != 0) or not (("resticprofile version " + resticprofile_version) in resticprofile_installed_version.stdout)

- name: Install resticprofile binary to /usr/bin
  copy:
    src: /tmp/resticprofile
    dest: /usr/bin/resticprofile
    remote_src: true
    mode: 751
    owner: root
    group: root
  become: true
  when: (resticprofile_installed.rc != 0) or not (("resticprofile version " + resticprofile_version) in resticprofile_installed_version.stdout)
